# Generated by Django 4.0 on 2022-04-15 12:32

import cloudinary.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import open_fitness_calculator.core.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaloriesPieChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
            ],
            bases=(models.Model, open_fitness_calculator.core.mixins.BaseDiaryCaloriesPieChartMixin),
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=datetime.date.today, max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Diaries',
            },
        ),
        migrations.CreateModel(
            name='MacrosPieChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
                ('diary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diary.diary')),
            ],
            bases=(models.Model, open_fitness_calculator.core.mixins.BaseDiaryMacrosPieChartMixin),
        ),
    ]
