# Generated by Django 4.0 on 2022-04-14 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='caloriespiechart',
            name='diary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diary.diary'),
        ),
    ]
