# Generated by Django 4.0 on 2022-04-12 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='name',
            field=models.CharField(blank=True, default=datetime.date.today, max_length=100),
        ),
    ]
