# Generated by Django 4.0 on 2022-04-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='unit',
            field=models.CharField(choices=[('minutes', 'minutes'), ('hours', 'hours'), ('sets', 'sets')], max_length=7),
        ),
    ]
